### PR TITLE
Recommendations

### PR DESCRIPTION
**Pull request by majora2007**
This PR adds the ability to fetch a paged list of recommendations from a given media entry. 

In addition, this addresses #7 due to not being able to run unit tests. 

Please advise if I need to address anything.

### CODE REVIEW

**Comment by dentolos19** [comment]
Thanks for the new feature!

**Comment by majora2007** [comment]
No problem. Any chance to get a release pushed?

**Comment by dentolos19** [comment]
I'll try to push a new release as soon as possible! Maybe I'll try to finish some [todo items](https://github.com/dentolos19/AniListNet#-todo) while I'm at it.

**Comment by majora2007** [comment]
If you'd like, I can help out. I need the recommendation feature for something I'm working on this week, so anything I can do to help to speed up the release, I will. 

I was planning to add AniList documentation to all the DTOs already, so let me take care of that one today.

**Comment by dentolos19** [comment]
Any help would be great!

I'll be pushing a new release on Friday. Any new feature/fixes made will be added to the new release.

**Pull request merged**
